name: Build and Release

on:
  push:
    tags:
      - 'v*'

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  build-and-release:
    name: Build and Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust Toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-unknown-linux-musl

      - name: Install musl tools
        run: |
          sudo apt-get update
          sudo apt-get install -y musl-tools musl-dev

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-musl-${{ hashFiles('**/Cargo.lock') }}

      - name: Build release version
        run: |
          cargo build --release --target x86_64-unknown-linux-musl

      - name: Prepare release files
        run: |
          mkdir -p release
          cp target/x86_64-unknown-linux-musl/release/lycrex-home release/
          cd release && tar -czf lycrex-home-linux-x86_64.tar.gz lycrex-home
          cd ..

      - name: Get version information
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Get commit messages
        id: get_commits
        run: |
          PREVIOUS_TAG=$(git describe --tags --abbrev=0 HEAD^ 2>/dev/null || echo "")
          if [ -z "$PREVIOUS_TAG" ]; then
            # 如果没有之前的标签，获取所有提交
            COMMITS=$(git log --pretty=format:"* %s (%h)" HEAD)
          else
            # 获取从上一个标签到当前标签的所有提交
            COMMITS=$(git log --pretty=format:"* %s (%h)" ${PREVIOUS_TAG}..HEAD)
          fi
          echo "COMMITS<<EOF" >> $GITHUB_OUTPUT
          echo "$COMMITS" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Release ${{ steps.get_version.outputs.VERSION }}
          draft: false
          prerelease: false
          files: |
            release/lycrex-home-linux-x86_64.tar.gz
          body: |
            ${{ steps.get_commits.outputs.COMMITS }} 